image:
  name: sonarsource/sonar-scanner-cli:latest
  entrypoint: ['']

before_script:
  - echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} >> .npmrc

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm/
    - node_modules

stages:
  - install
  - test
  - sonarqube

install:
  stage: install
  script: npm install --cache .npm --prefer-offline
  artifacts:
    paths:
      - node_modules
  only:
    - merge_requests
    - master

test:
  stage: test
  script:
    - npm run test
  artifacts:
    paths:
      - coverage

  only:
    - merge_requests
    - master

sonarqube:
  stage: sonarqube
  script:
    - npm run lint:report
    - CURRENT_VERSION=$(node -p "require('./package.json').version")
    - |
      sonar-scanner \
        -Dsonar.qualitygate.wait=true \
        -Dsonar.sources=app \
        -Dsonar.host.url=$SONAR_HOST_URL \
        -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info \
        -Dsonar.exclusions=**/*.test.*,**/app.tsx,**/fontawesome/**/*,__mocks__/**/* \
        -Dsonar.eslint.reportPaths=report.json \
        -Dsonar.projectVersion=$CURRENT_VERSION \
        -Dsonar.projectKey=pp-frontend
  only:
    - merge_requests
    - master
